import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    code: 'en', label: 'English', flag: '🇬🇧',
    home: 'Home', shop: 'Shop', running: 'Running', sneakers: 'Sneakers',
    basketball: 'Basketball', boots: 'Boots', wishlist: 'Wishlist',
    cart: 'Cart', login: 'Login', logout: 'Logout', signup: 'Sign Up',
    myOrders: 'My Orders', adminPanel: 'Admin Panel',
    searchPlaceholder: 'Search shoes...',
    heroTag: 'New Collection 2024',
    heroTitle1: 'STEP INTO', heroTitle2: 'GREATNESS',
    heroDesc: 'Premium shoes crafted for every lifestyle. From track to street, find your perfect pair at Foot Rush.',
    shopNow: 'Shop Now', newArrivals: 'New Arrivals',
    freeShipping: 'Free Shipping', freeShippingDesc: 'On all orders over ₹8,400',
    warranty: '2-Year Warranty', warrantyDesc: 'Full coverage guarantee',
    returns: '30-Day Returns', returnsDesc: 'Hassle-free returns',
    quality: 'Premium Quality', qualityDesc: 'Handpicked materials',
    browseBy: 'Browse By', categories: 'Categories', viewAll: 'View All',
    topPicks: 'Top Picks', featuredProducts: 'Featured Products', shopAll: 'Shop All',
    builtFor: 'Built For Champions',
    builtDesc: 'At Foot Rush, we believe every step tells a story. Our shoes are designed with precision, crafted with care, and built to take you further than you ever imagined.',
    exploreCollection: 'Explore Collection',
    customerSay: 'What Our Customers Say', reviews: 'Reviews',
    addToCart: 'Add to Cart', quickAdd: 'Quick Add',
    selectSize: 'Select Size', quantity: 'Quantity',
    proceedCheckout: 'Proceed to Checkout', continueShopping: 'Continue Shopping',
    orderSummary: 'Order Summary', subtotal: 'Subtotal', shipping: 'Shipping',
    tax: 'Estimated Tax', total: 'Total', free: 'FREE',
    placeOrder: 'Place Order', shippingInfo: 'Shipping Information',
    paymentDetails: 'Payment Details', reviewOrder: 'Review Your Order',
    allShoes: 'All Shoes', noResults: 'No shoes found',
    onlyLeft: 'Only', left: 'left',
    size: 'Size', brand: 'Brand',
  },
  hi: {
    code: 'hi', label: 'हिन्दी', flag: '🇮🇳',
    home: 'होम', shop: 'शॉप', running: 'रनिंग', sneakers: 'स्नीकर्स',
    basketball: 'बास्केटबॉल', boots: 'बूट्स', wishlist: 'विशलिस्ट',
    cart: 'कार्ट', login: 'लॉगिन', logout: 'लॉगआउट', signup: 'साइन अप',
    myOrders: 'मेरे ऑर्डर', adminPanel: 'एडमिन पैनल',
    searchPlaceholder: 'जूते खोजें...',
    heroTag: 'नया कलेक्शन 2024',
    heroTitle1: 'कदम रखो', heroTitle2: 'महानता में',
    heroDesc: 'हर जीवनशैली के लिए प्रीमियम जूते। ट्रैक से सड़क तक, Foot Rush पर अपनी परफेक्ट जोड़ी पाएं।',
    shopNow: 'अभी खरीदें', newArrivals: 'नए आइटम',
    freeShipping: 'मुफ्त शिपिंग', freeShippingDesc: '₹8,400 से ऊपर के सभी ऑर्डर पर',
    warranty: '2 साल की वारंटी', warrantyDesc: 'पूरी कवरेज गारंटी',
    returns: '30 दिन वापसी', returnsDesc: 'आसान वापसी प्रक्रिया',
    quality: 'प्रीमियम गुणवत्ता', qualityDesc: 'चुने हुए सामग्री',
    browseBy: 'ब्राउज़ करें', categories: 'श्रेणियाँ', viewAll: 'सभी देखें',
    topPicks: 'टॉप पिक्स', featuredProducts: 'फीचर्ड प्रोडक्ट्स', shopAll: 'सभी खरीदें',
    builtFor: 'चैंपियंस के लिए बना',
    builtDesc: 'Foot Rush में हम मानते हैं कि हर कदम एक कहानी कहता है।',
    exploreCollection: 'कलेक्शन देखें',
    customerSay: 'ग्राहक क्या कहते हैं', reviews: 'समीक्षाएं',
    addToCart: 'कार्ट में जोड़ें', quickAdd: 'जल्दी जोड़ें',
    selectSize: 'साइज़ चुनें', quantity: 'मात्रा',
    proceedCheckout: 'चेकआउट करें', continueShopping: 'खरीदारी जारी रखें',
    orderSummary: 'ऑर्डर सारांश', subtotal: 'उप-कुल', shipping: 'शिपिंग',
    tax: 'अनुमानित कर', total: 'कुल', free: 'मुफ्त',
    placeOrder: 'ऑर्डर दें', shippingInfo: 'शिपिंग जानकारी',
    paymentDetails: 'भुगतान विवरण', reviewOrder: 'ऑर्डर समीक्षा करें',
    allShoes: 'सभी जूते', noResults: 'कोई जूते नहीं मिले',
    onlyLeft: 'केवल', left: 'बचे',
    size: 'साइज़', brand: 'ब्रांड',
  },
  es: {
    code: 'es', label: 'Español', flag: '🇪🇸',
    home: 'Inicio', shop: 'Tienda', running: 'Running', sneakers: 'Zapatillas',
    basketball: 'Baloncesto', boots: 'Botas', wishlist: 'Favoritos',
    cart: 'Carrito', login: 'Iniciar sesión', logout: 'Cerrar sesión', signup: 'Registrarse',
    myOrders: 'Mis Pedidos', adminPanel: 'Panel Admin',
    searchPlaceholder: 'Buscar zapatos...',
    heroTag: 'Nueva Colección 2024',
    heroTitle1: 'ENTRA EN LA', heroTitle2: 'GRANDEZA',
    heroDesc: 'Zapatos premium para cada estilo de vida. Desde la pista hasta la calle, encuentra tu par perfecto en Foot Rush.',
    shopNow: 'Comprar Ahora', newArrivals: 'Novedades',
    freeShipping: 'Envío Gratis', freeShippingDesc: 'En pedidos sobre ₹8,400',
    warranty: 'Garantía 2 Años', warrantyDesc: 'Cobertura completa garantizada',
    returns: 'Devoluciones 30 días', returnsDesc: 'Devoluciones sin complicaciones',
    quality: 'Calidad Premium', qualityDesc: 'Materiales seleccionados',
    browseBy: 'Explorar Por', categories: 'Categorías', viewAll: 'Ver Todo',
    topPicks: 'Selección Top', featuredProducts: 'Productos Destacados', shopAll: 'Ver Todo',
    builtFor: 'Hecho Para Campeones',
    builtDesc: 'En Foot Rush creemos que cada paso cuenta una historia.',
    exploreCollection: 'Explorar Colección',
    customerSay: 'Lo Que Dicen Nuestros Clientes', reviews: 'Reseñas',
    addToCart: 'Agregar al Carrito', quickAdd: 'Agregar Rápido',
    selectSize: 'Seleccionar Talla', quantity: 'Cantidad',
    proceedCheckout: 'Proceder al Pago', continueShopping: 'Seguir Comprando',
    orderSummary: 'Resumen del Pedido', subtotal: 'Subtotal', shipping: 'Envío',
    tax: 'Impuesto Estimado', total: 'Total', free: 'GRATIS',
    placeOrder: 'Realizar Pedido', shippingInfo: 'Información de Envío',
    paymentDetails: 'Detalles de Pago', reviewOrder: 'Revisar Pedido',
    allShoes: 'Todos los Zapatos', noResults: 'No se encontraron zapatos',
    onlyLeft: 'Solo', left: 'quedan',
    size: 'Talla', brand: 'Marca',
  },
  fr: {
    code: 'fr', label: 'Français', flag: '🇫🇷',
    home: 'Accueil', shop: 'Boutique', running: 'Running', sneakers: 'Baskets',
    basketball: 'Basketball', boots: 'Bottes', wishlist: 'Favoris',
    cart: 'Panier', login: 'Connexion', logout: 'Déconnexion', signup: "S'inscrire",
    myOrders: 'Mes Commandes', adminPanel: 'Panneau Admin',
    searchPlaceholder: 'Rechercher des chaussures...',
    heroTag: 'Nouvelle Collection 2024',
    heroTitle1: 'ENTREZ DANS LA', heroTitle2: 'GRANDEUR',
    heroDesc: 'Chaussures premium pour chaque style de vie. De la piste à la rue, trouvez votre paire parfaite chez Foot Rush.',
    shopNow: 'Acheter Maintenant', newArrivals: 'Nouveautés',
    freeShipping: 'Livraison Gratuite', freeShippingDesc: 'Sur toutes les commandes de plus de ₹8 400',
    warranty: 'Garantie 2 Ans', warrantyDesc: 'Couverture complète garantie',
    returns: 'Retours 30 Jours', returnsDesc: 'Retours sans tracas',
    quality: 'Qualité Premium', qualityDesc: 'Matériaux sélectionnés',
    browseBy: 'Parcourir Par', categories: 'Catégories', viewAll: 'Voir Tout',
    topPicks: 'Sélection Top', featuredProducts: 'Produits Vedettes', shopAll: 'Voir Tout',
    builtFor: 'Fait Pour les Champions',
    builtDesc: 'Chez Foot Rush, nous croyons que chaque pas raconte une histoire.',
    exploreCollection: 'Explorer la Collection',
    customerSay: 'Ce que Disent Nos Clients', reviews: 'Avis',
    addToCart: 'Ajouter au Panier', quickAdd: 'Ajout Rapide',
    selectSize: 'Choisir la Taille', quantity: 'Quantité',
    proceedCheckout: 'Passer la Commande', continueShopping: 'Continuer les Achats',
    orderSummary: 'Récapitulatif', subtotal: 'Sous-total', shipping: 'Livraison',
    tax: 'Taxe Estimée', total: 'Total', free: 'GRATUIT',
    placeOrder: 'Passer la Commande', shippingInfo: 'Informations de Livraison',
    paymentDetails: 'Détails de Paiement', reviewOrder: 'Vérifier la Commande',
    allShoes: 'Toutes les Chaussures', noResults: 'Aucune chaussure trouvée',
    onlyLeft: 'Seulement', left: 'restants',
    size: 'Taille', brand: 'Marque',
  },
  ar: {
    code: 'ar', label: 'العربية', flag: '🇸🇦',
    home: 'الرئيسية', shop: 'المتجر', running: 'ركض', sneakers: 'أحذية رياضية',
    basketball: 'كرة السلة', boots: 'أحذية', wishlist: 'المفضلة',
    cart: 'السلة', login: 'تسجيل الدخول', logout: 'تسجيل الخروج', signup: 'إنشاء حساب',
    myOrders: 'طلباتي', adminPanel: 'لوحة الإدارة',
    searchPlaceholder: 'ابحث عن أحذية...',
    heroTag: 'مجموعة جديدة 2024',
    heroTitle1: 'خطوا نحو', heroTitle2: 'العظمة',
    heroDesc: 'أحذية فاخرة لكل أسلوب حياة. من المضمار إلى الشارع، اعثر على زوجك المثالي في Foot Rush.',
    shopNow: 'تسوق الآن', newArrivals: 'وصل حديثاً',
    freeShipping: 'شحن مجاني', freeShippingDesc: 'على جميع الطلبات فوق ₹8,400',
    warranty: 'ضمان سنتين', warrantyDesc: 'ضمان تغطية كاملة',
    returns: 'إرجاع 30 يوم', returnsDesc: 'إرجاع سهل وبسيط',
    quality: 'جودة فاخرة', qualityDesc: 'مواد مختارة بعناية',
    browseBy: 'تصفح حسب', categories: 'الفئات', viewAll: 'عرض الكل',
    topPicks: 'أفضل الاختيارات', featuredProducts: 'منتجات مميزة', shopAll: 'تسوق الكل',
    builtFor: 'مصنوع للأبطال',
    builtDesc: 'في Foot Rush نؤمن أن كل خطوة تحكي قصة.',
    exploreCollection: 'استكشف المجموعة',
    customerSay: 'ماذا يقول عملاؤنا', reviews: 'التقييمات',
    addToCart: 'أضف إلى السلة', quickAdd: 'إضافة سريعة',
    selectSize: 'اختر المقاس', quantity: 'الكمية',
    proceedCheckout: 'إتمام الشراء', continueShopping: 'مواصلة التسوق',
    orderSummary: 'ملخص الطلب', subtotal: 'المجموع الفرعي', shipping: 'الشحن',
    tax: 'الضريبة المقدرة', total: 'الإجمالي', free: 'مجاني',
    placeOrder: 'تأكيد الطلب', shippingInfo: 'معلومات الشحن',
    paymentDetails: 'تفاصيل الدفع', reviewOrder: 'مراجعة الطلب',
    allShoes: 'جميع الأحذية', noResults: 'لم يتم العثور على أحذية',
    onlyLeft: 'فقط', left: 'متبقي',
    size: 'المقاس', brand: 'الماركة',
  },
}

const LanguageContext = createContext(null)

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('footrush_lang') || 'en')

  const changeLang = (code) => {
    setLang(code)
    localStorage.setItem('footrush_lang', code)
    document.documentElement.dir = code === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = code
  }

  const t = translations[lang] || translations.en

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, languages: Object.values(translations).map(l => ({ code: l.code, label: l.label, flag: l.flag })) }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider')
  return ctx
}
